name: "mnist_pretrained"
backend: "onnxruntime"

max_batch_size: 32

input:
  - name: "Input3"
    data_type: "FP32"
    dims: [1, 28, 28]

output:
  - name: "Plus214_Output_0"
    data_type: "FP32"
    dims: [10]

preprocess:
  resize: [28, 28]
  mean: [0.5]
  std: [0.5]
  pixel_format: "GRAY"

label_map: "char2idx.txt"

backend_config:
  providers:
    - name: "CPUExecutionProvider"
