# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"N\n\x11ModelInferRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12%\n\x06inputs\x18\x02 \x03(\x0b\x32\x15.inference.InferInput\"M\n\nInferInput\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\x10\n\x08\x64\x61tatype\x18\x03 \x01(\t\x12\x10\n\x08raw_data\x18\x04 \x01(\x0c\"Q\n\x12ModelInferResponse\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\'\n\x07outputs\x18\x02 \x03(\x0b\x32\x16.inference.InferOutput\"N\n\x0bInferOutput\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\x10\n\x08\x64\x61tatype\x18\x03 \x01(\t\x12\x10\n\x08raw_data\x18\x04 \x01(\x0c\"\'\n\x11ModelReadyRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\"#\n\x12ModelReadyResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x32\xa8\x01\n\x10InferenceService\x12I\n\nModelInfer\x12\x1c.inference.ModelInferRequest\x1a\x1d.inference.ModelInferResponse\x12I\n\nModelReady\x12\x1c.inference.ModelReadyRequest\x1a\x1d.inference.ModelReadyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELINFERREQUEST']._serialized_start=30
  _globals['_MODELINFERREQUEST']._serialized_end=108
  _globals['_INFERINPUT']._serialized_start=110
  _globals['_INFERINPUT']._serialized_end=187
  _globals['_MODELINFERRESPONSE']._serialized_start=189
  _globals['_MODELINFERRESPONSE']._serialized_end=270
  _globals['_INFEROUTPUT']._serialized_start=272
  _globals['_INFEROUTPUT']._serialized_end=350
  _globals['_MODELREADYREQUEST']._serialized_start=352
  _globals['_MODELREADYREQUEST']._serialized_end=391
  _globals['_MODELREADYRESPONSE']._serialized_start=393
  _globals['_MODELREADYRESPONSE']._serialized_end=428
  _globals['_INFERENCESERVICE']._serialized_start=431
  _globals['_INFERENCESERVICE']._serialized_end=599
# @@protoc_insertion_point(module_scope)
